on:
    workflow_dispatch:
    release:
        types: [published]
    push:
        branches:
            - main
            - master
        paths:
            - "**/*.go"
            - "go.mod"
            - "go.sum"
            - ".github/workflows/*.yml"
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - "**/*.go"
            - "go.mod"
            - "go.sum"
            - ".github/workflows/*.yml"

name: Build Release
jobs:
    Build:
        permissions:
            contents: write
        strategy:
            matrix:
                # Include amd64 on all platforms.
                goos: [linux, darwin]
                goarch: [amd64]
                exclude:
                    # Exclude i386 on darwin and dragonfly.
                    - goarch: 386
                      goos: dragonfly
                    - goarch: 386
                      goos: darwin
                include:
                    # BEIGIN MacOS ARM64
                    - goos: darwin
                      goarch: arm64
                    # END MacOS ARM64
                    # BEGIN Linux ARM 5 6 7
                    - goos: linux
                      goarch: arm
                      goarm: 7
          
                    # END Linux ARM 5 6 7
                    # BEGIN Android ARM 8
                    - goos: android
                      goarch: arm64
                    # END Android ARM 8
                    # BEGIN Other architectures
                    # BEGIN riscv64 & ARM64
                    - goos: linux
                      goarch: arm64
                   
            fail-fast: false

        runs-on: ubuntu-latest
        env:
            GOOS: ${{ matrix.goos }}
            GOARCH: ${{ matrix.goarch }}
            GOARM: ${{ matrix.goarm }}
            CGO_ENABLED: 0
        steps:
            - name: Checkout codebase
              uses: actions/checkout@v3

            - name: Show workflow information
              run: |
                  export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM$GOMIPS\"].friendlyName" -r < .github/build/friendly-filenames.json)
                  echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, GOMIPS: $GOMIPS, RELEASE_NAME: $_NAME"
                  echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23.2"
                  check-latest: true

            - name: Get project dependencies
              run: go mod download

            - name: Build
              run: |
                  mkdir -p build_assets
                  go build -v -o build_assets/ORMEncryption -trimpath -ldflags "-s -w -buildid=" ./

            #   - name: Upload binaries to release
            #     uses: svenstaro/upload-release-action@v2
            #     if: github.event_name == 'release'
            #     with:
            #       repo_token: ${{ secrets.GT_Token }}
            #       file: ./ORMEncryption-${{ env.ASSET_NAME }}.zip*
            #       tag: ${{ github.ref }}
            #       file_glob: true
            - uses: christopherhx/gitea-upload-artifact@v4
              with:
                  name: ORMEncryption-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}
                  path: build_assets/ORMEncryption
